INSERT INTO PRODUCTS (TYPE,NAME, DESCRIPTION) VALUES 
('pizza', 'PIZZA NAME1', 'PIZZA DESCR'),
('pizza', 'PIZZA NAME2', 'PIZZA DESCR'),
('pizza', 'PIZZA NAME3', 'PIZZA DESCR'),
('pizza', 'PIZZA NAME4', 'PIZZA DESCR'),
('pizza', 'PIZZA NAME5', 'PIZZA DESCR'),
('pizza', 'PIZZA NAME6', 'PIZZA DESCR'),
('additive', 'ADDITIVE NAME1', 'ADDITIVE DESCR'),
('additive', 'ADDITIVE NAME2', 'ADDITIVE DESCR'),
('additive', 'ADDITIVE NAME3', 'ADDITIVE DESCR'),
('additive', 'ADDITIVE NAME4', 'ADDITIVE DESCR'),
('additive', 'ADDITIVE NAME5', 'ADDITIVE DESCR');

SELECT * FROM PRODUCTS;

INSERT INTO MANUFACTURERS (NAME, GAIN) VALUES
('PIZZERIA1', 3),
('PIZZERIA2', 5),
('PIZZERIA3', 8),
('PIZZERIA4', 7),
('PIZZERIA5', 6);

SELECT * FROM MANUFACTURERS;

INSERT INTO CLIENTS (NAME, TEL) VALUES
('CLIENT1', '0123456789'),
('CLIENT2', '1987456123'),
('CLIENT3', '0258963147'),
('CLIENT4', '0963258741'),
('CLIENT5', '0582147936'),
('CLIENT6', '0357894136');